### ISSUE TITLE
Sélection des images

### ISSUE THREAD

**Issue by PonteIneptique** [HTR-United/CREMMA-AN-TestamentDePoilus#1]
Contrairement aux autres corpus d'alignement CREMMA, une stratégie de sélection semi-aléatoire serait ici plus intéressante. 

Je propose dans un premier temps de sélectionner les documents en fonction du département de naissance du poilu, à raison d'un document par département ?

**Comment by PonteIneptique** [comment]
(je mettrais à disposition des scripts en fonction des décisions)

**Comment by alix-tz** [comment]
Ça marche, je pense que c'est le plus simple à viser. Après on pourra ajouter la dimension socioprofessionnelle, qui pourrait être un variant intéressant. 

A titre personnel, je suis prête à faire un peu d'alignement moi aussi.
