### ISSUE TITLE
Faire alignement pour batch 1

### ISSUE THREAD

**Issue by alix-tz** [HTR-United/CREMMA-AN-TestamentDePoilus#12]

**Comment by alix-tz** [comment]
Hello @ElsaVK et @AnaisMazoue !

Un petit retour après avoir jeté un oeil aux documents du batch1 sur eScriptorium. 

J'ai l'impression que vous avez fait de la transcription from scratch. Mais il y a déjà une transcription (produite dans le cadre de Testament de Poilus), qu'il faut simplement copier-coller sur les lignes de la zone principale.

EDIT: je précise que les transcriptions sont dans le dossier batch1/ (1 fichier txt par liasse, avec "[Page]" qui marque la séparation entre les pages (et donc les images)).

Les zones ne sont pas toujours bien dessinées : 
- il faut une zone "MainZone" correspondant à la zone entre batons
- pour les tampons ou les zones marginale, ne faites pas une zone par ligne mais une zone par ensemble logique

Par ailleurs, inutile de transcrire les mentions marginales et les portions manuscrites des tampons. Vous pouvez associer ces éléments à une zone "StampZone" par exemple, mais laissez-la vide. 



Je pense d'ailleurs que vous n'avez pas besoin d'autant d'éléments issu de SegmOnto. Je pense que "MainZone" + "DefaultLine" devraient suffire. Avec en plus, si vous voulez prendre le temps de faire cela, "StampZone", "MarginTextZone" mais ce n'est pas nécessaire. 

![image](https://user-images.githubusercontent.com/33317799/201760064-535abdd5-a84c-4c11-bcd1-815ab9cceb98.png)

**Comment by alix-tz** [comment]
Je vous mets un exemple d'un cas que j'ai corrigé :

![image](https://user-images.githubusercontent.com/33317799/201759117-b95ab7f3-bbda-46a1-b7de-aec660f30f84.png)

corrigé: 
![image](https://user-images.githubusercontent.com/33317799/201759719-7a5a659a-9656-4782-aa1c-17c2e3aac344.png)

**Comment by alix-tz** [comment]
N'hésitez pas à m'écrire ici ou par mail si vous avez des questions, et vous avez aussi les documents du batch2 comme modèle si jamais vous avez une doute ! :)

**Comment by ElsaVK** [comment]
Merci Alix pour tes précisions ! Il me reste une dizaine d'heures à faire, je vais essayer de faire ça le plus proprement possible ;)

A très vite,

Elsa



De : Alix Chagué ***@***.***>
À : HTR-United/CREMMA-AN-TestamentDePoilus ***@***.***>
Sujet : Re: [HTR-United/CREMMA-AN-TestamentDePoilus] Faire alignement pour batch 1 (Issue #12)
Date : 14/11/2022 21:36:14 Europe/Paris
Copie à : Elsa Van Kote ***@***.***>;
   Mention ***@***.***>


N'hésitez pas à m'écrire ici ou par mail si vous avez des questions, et vous avez aussi les documents du batch2 comme modèle si jamais vous avez une doute ! :)
