### ISSUE TITLE
All images under /data are truncated

### ISSUE THREAD

**Issue by johngrabner** [HTR-United/CREMMA-AN-TestamentDePoilus#14]
Do you have full-page images?

**Comment by PonteIneptique** [comment]
Hey,
I think you are just looking at the preview images, because all images are full. Click download on the home page or simply download on the top right corner of each image.
![image](https://user-images.githubusercontent.com/1929830/191667959-58f8c41d-79e4-4150-8fce-40e00421d9eb.png)
