### ISSUE TITLE
License ?

### ISSUE THREAD

**Issue by alix-tz** [HTR-United/CREMMA-AN-TestamentDePoilus#15]
On ne devrait pas avoir une license dans ce repo ?

**Comment by PonteIneptique** [comment]
Pas obligatoire mais pas interdit :D

**Comment by alix-tz** [comment]
@florenceclavaud Avez-vous une license associée aux données de Testaments de Poilus ?

**Comment by PonteIneptique** [comment]
Au dernier meeting aux AN, c'était CC BY (j'ai un doute sur -SA)

**Comment by florenceclavaud** [comment]
Hello, oui je confirme, voir https://github.com/ArchivesNationalesFR/editionTestamentsDePoilus

**Comment by alix-tz** [comment]
Merci Florence!
