### ISSUE TITLE
Faire une branche sans les images ?

### ISSUE THREAD

**Issue by alix-tz** [HTR-United/CREMMA-AN-TestamentDePoilus#2]
J'essaie de télécharger le repo pour faire un deuxième batch, mais les images sont lourdes. Est-ce qu'on peut envisager une version "light" du repo ?

**Comment by alix-tz** [comment]
Je précise, ce n'est pas urgent, mais au fur et à mesure qu'on va ajouter des batch, ça risque de peser lourd

**Comment by PonteIneptique** [comment]
Alors personnellement, je vois mal qui voudrait télécharger les ALTO sans les images. :D

**Comment by alix-tz** [comment]
C'est surtout pour les cas où tu veux télécharger le repo pour créer un nouveau batch, pas pour l'utilisation de la vérité de terrain elle-même. Mais bon, j'admets que l'idée est saugrenue !🤷

**Comment by PonteIneptique** [comment]
Fixed
