### ISSUE TITLE
Faire alignement pour batch 2

### ISSUE THREAD

**Issue by alix-tz** [HTR-United/CREMMA-AN-TestamentDePoilus#5]
Je crée cette issue pour garder une trace de ma progression et d'éventuelles questions qui se poseraient en cours de route.

**Comment by alix-tz** [comment]
Les portions barrés ont souvent été transcris malgré tout. Ajoute-t-on un symbole pour signaler cela ?

(sur https://escriptorium.inria.fr/document/1547/part/134282/ )
![image](https://user-images.githubusercontent.com/33317799/158467936-b60e4e91-3b68-4cf3-b31f-7b32a7c66496.png)

**Comment by alix-tz** [comment]
Quelques rares cas où le mot est "découpé" en raison de l'état du papier. Signale-t-on cela ? 

(sur https://escriptorium.inria.fr/document/1547/part/134282/ )

![image](https://user-images.githubusercontent.com/33317799/158468210-691a7731-7226-416e-bc36-331f470cd01f.png)

**Comment by alix-tz** [comment]
Le développement des abréviations n'étant pas systématique (et parfois un peu problématique car la forme développée relève plus de la désambiguïsation) , je n'ai gardé que les formes abrégées. 

Les portions suscrites sont signalée par `mot non suscrit^suscrit`

| Forme retenue `| Forme non retenue | 
| :---------------- | :---------------------- |
| ![image](https://user-images.githubusercontent.com/33317799/158468969-00ac12a9-33ac-41de-9b4a-9231cc152eef.png) | ![image](https://user-images.githubusercontent.com/33317799/158468868-014b72d8-2d39-461f-9138-2feb62c1352e.png) | 
| ![image](https://user-images.githubusercontent.com/33317799/158472430-413491a9-23c8-4c22-ba75-8e1c85754cc6.png) |  ![image](https://user-images.githubusercontent.com/33317799/158472342-5b08e31c-dfab-4647-bac9-70f8953574e2.png) |

**Comment by PonteIneptique** [comment]
Fixed by #8
